fps: 60
model_path: '/home/jakejoseph/Desktop/HumanHand-Jake-2024-07-16/exported-models/DLC_HumanHand_resnet_50_iteration-1_shuffle-1'
video_path: '/home/jakejoseph/Desktop/Joseph_Code/FESFatigue-Jake-2024-05-31/videos/napierecrbfatigue_05_31_3_1.mp4'
resize: 0.5
