camera_params:
  resolution:
    width: 640
    height: 480
  fps: "100/1"
active_cameras:
  - camera:
      name: "top"
      serial: "123456"
inactive_cameras:
  - camera:
      name: "left"
      serial: "123456"
      resolution:
        width: 640
        height: 480
      fps: "100/1"
      format: "BGRx"      
  - camera:
      name: "right"
      serial: "123456"
      resolution:
        width: 640
        height: 480
      fps: "100/1"
      format: "BGRx"